name: build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.image.name }}
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        image:
          - path: guest/fedora/41
            name: guest-fedora-41
          - path: guest/ubuntu/oracular
            name: guest-ubuntu-oracular
          - path: guest/debian/bookworm
            name: guest-debian-bookworm

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo sed -i 's/noble/plucky/g' /etc/apt/sources.list.d/ubuntu.sources
          sudo apt update
          sudo apt install -y mkosi

      - name: Build ${{ matrix.image.name }}
        run: |
          sudo mkosi -C ${{ matrix.image.path }}/ cat-config
          sudo mkosi -C ${{ matrix.image.path }}/ summary
          sudo mkosi -C ${{ matrix.image.path }}/ build

      - name: Convert raw image to qcow2
        run: |
          qemu-img convert -f raw -O qcow2 ${{ matrix.image.path }}/image.raw ${{ matrix.image.path }}/image.qcow2

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.image.name }}
          path: |
            ${{ matrix.image.path }}/image.efi
            ${{ matrix.image.path }}/image.qcow2
          retention-days: 7
