on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    strategy:
      matrix:
        image:
          - guest-fedora-41

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: dnf install -y mkosi qemu-img systemd-ukify systemd-udev policycoreutils mtools

      - name: Build ${{ matrix.image }}
        run: sudo mkosi -C ${{ matrix.image }}/

      - name: Convert raw image to qcow2
        run: |
          qemu-img convert -f raw -O qcow2 ${{ matrix.image }}/image.raw ${{ matrix.image }}/image.qcow2

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.image }}
          path: |
            ${{ matrix.image }}/image.efi
            ${{ matrix.image }}/image.qcow2
          retention-days: 7
