name: publish-latest-images
on:
  workflow_run:
    workflows: ["build-host", "build-guest"]
    types: [completed]

jobs:
  release-host:
    if: ${{ github.event.workflow_run.name == 'build-host' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download host artifacts
        uses: dawidd6/action-download-artifact@v11
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          run_id: ${{ github.event.workflow_run.id }}
          path: dist/host

      - name: Update latest
        run: |
          gh release delete development-host --cleanup-tag --yes || true
          gh release create development-host dist/host/**/*.efi --title "Development Host Images" --notes "Automated build of host images from main branch." --prerelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-guest:
    if: ${{ github.event.workflow_run.name == 'build-guest' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download guest artifacts
        uses: dawidd6/action-download-artifact@v11
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          run_id: ${{ github.event.workflow_run.id }}
          path: dist/guest

      - name: Update latest
        run: |
          gh release delete development-guest --cleanup-tag --yes || true
          gh release create development-guest dist/guest/**/*.efi --title "Development Guest Images" --notes "Automated build of guest images from main branch." --prerelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}