name: dispatch CI

on:
  push:
    branches: [ main ]
    paths:
      - 'dispatch/**'
      - '.github/workflows/dispatch-ci.yml'
  pull_request:
    paths:
      - 'dispatch/**'
      - '.github/workflows/dispatch-ci.yml'

permissions:
  contents: read

jobs:
  build-test:
    name: Build, Lint, Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dispatch
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust (nightly)
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt
          targets: x86_64-unknown-uefi

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            dispatch -> dispatch/target

      - name: Verify formatting
        run: cargo fmt --all -- --check

      - name: Clippy lint
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build
        run: cargo build --locked --all-targets

      - name: Build (release)
        run: cargo build --locked --release

      - name: Test
        run: cargo test --locked --all-targets -- --nocapture

  static-builds:
    name: Static Binary Builds
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            name: dispatch-linux-x86_64
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: dispatch
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust (nightly)
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ matrix.target }},x86_64-unknown-uefi

      - name: Install musl-tools
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            dispatch -> dispatch/target

      - name: Build static release
        run: |
          RUSTFLAGS='-C target-feature=+crt-static' \
          cargo build --locked --release --target ${{ matrix.target }}

      - name: Verify static linking
        run: |
          file target/${{ matrix.target }}/release/dispatch
          ldd target/${{ matrix.target }}/release/dispatch || echo "Static binary confirmed"

      - name: Rename binary
        run: |
          mkdir -p ../artifacts
          cp target/${{ matrix.target }}/release/dispatch ../artifacts/${{ matrix.name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: artifacts/${{ matrix.name }}
          retention-days: 30
